baseURL = "https://amanahuja.me/"
languageCode = "en-us"
title = "Aman Ahuja"

# https://github.com/theNewDynamic/gohugo-theme-ananke
theme = "amanophonic"

Paginate = 4
googleAnalytics = "UA-30448018-1"
enableRobotsTXT = true

[params]
  # General info
  description = "Aman Ahuja's website."
  orgName = "Aman Ahuja"

  # base style
  favicon = "/img/favicon.ico?v=0"
  logo = "/img/blogophonic-mark-dark.png"

  # font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"

  # basic color options: use only color names as shown in the
  # "Color Palette" section of http://tachyons.io/docs/themes/skins/
  custom_css = ["assets/custom.css"]
  body_classes = "lato bg-near-white"
  siteBgColor = "near-white"
  textColor = "dark-gray"
  bodyLinkColor = "blue"

  sidebarBgColor = "light-gray"
  sidebarTextColor = "mid-gray"
  headlineColor = "red"
  headingColor = "near-black"
  navLinkColor = "near-black"
  sidebarLinkColor = "near-black"
  footerTextColor = "gray"

  buttonTextColor = "near-white"
  buttonBgColor = "black"
  buttonHoverTextColor = "white"
  buttonHoverBgColor = "blue"
  borderColor = "moon-gray"

  # show/hide social icons in site header/footer
  # content display
  recent_posts_number = 2
  show_reading_time = false

  socialInHeader = false
  socialInFooter = true

[social]
  github = "amanahuja"
  linkedin = "amanahuja"
  medium = ""
  twitter = "amanqa"
  youtube = ""
  # no SVG: rss = "index.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[sitemap] 
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
