baseURL = "http://amanahuja.me/"
languageCode = "en-us"
title = "Aman Ahuja"

# https://github.com/theNewDynamic/gohugo-theme-ananke
theme = "ananke"

# New for Ananke
# ----
# DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-30448018-1"
enableRobotsTXT = true

# old from theme playing
# ----
# author = "Aman"
# profilePicture = "images/profile.jpg"
# displayMode = "dark"

# [[menu.main]]
# name = "Posts"
# identifier = "posts"
# weight = 200
# url = "/post/"

[taxonomies]
    tag = "tags"
    category = "categories"
    mood = "moods"

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"

    # [[menu.main]]
    # name = "Manifesto"
    #identifier = "manifesto"
    # weight = 200
    #url = "/manifesto/"

    [[menu.main]]
    name = "Portfolio"
    identifier = "Portfolio"
    weight = 300
    url = "/Portfolio/"

[params]
  favicon = ""
  site_logo = ""
  # TODO: add to static directory and add here
  description = "Aman Ahuja's website."

  # Social: instagram, facebook, youtube, gitlab, mastodon, slack, stackoverflow, rss
  linkedin = "https://linkedin.com/in/amanahuja"
  twitter = "https://twitter.com/amanqa"

  # styling throughout site
  # reference: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-fa-blue"
  body_classes = "lato bg-near-white"
  custom_css = ["assets/custom.css"]

  # content display
  mainSections = ["disabledwithfakenamehere"]
  recent_posts_number = 2
  show_reading_time = true
