baseURL = "https://amanahuja.me/"
languageCode = "en-us"
title = "Aman Ahuja"

# https://github.com/theNewDynamic/gohugo-theme-ananke
theme = "amanophonic"

# check this for compatibility with quartz backlinks
relativeURLs = false

enableRobotsTXT = false

ignoreFiles = [
]

[pagination]
  pagerSize = 4

[params]
  # General info
  description = "Aman Ahuja's website."
  orgName = "Aman Ahuja"

  # base style
  favicon = "/images/favicon/favicon.ico?v=0"
  logo = "/images/logos/amanahuja_me.png"

  # font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"

  # basic color options: use only color names as shown in the
  # "Color Palette" section of http://tachyons.io/docs/themes/skins/
  custom_css = ["assets/custom.css"]
  body_classes = "lato bg-near-white"

  # color notes
  # favicon / logo : light-gray + black + white
  # accent : dark-green #137752
  # background: near-white: #F4F4F4
  # text: dark-gray: #333333
  # logo font: lora

  # 1 
  siteBgColor = "near-white" 
  textColor = "dark-gray"  
  bodyLinkColor = "dark-green"
  headlineColor = "near-black" 
  headingColor = "near-black"
  # headlineColor = "dark-green"
  # headingColor = "dark-green"
  
  # 2
  sidebarBgColor = "light-gray"
  sidebarTextColor = "mid-gray"
  navLinkColor = "near-black"
   
  # 3
  buttonTextColor = "dark-green"
  buttonBgColor = "moon-gray"
  buttonHoverTextColor = "moon-gray"
  buttonHoverBgColor = "dark-green"
  borderColor = "moon-gray"

  # buttonTextColor = "near-white"
  # buttonBgColor = "black"
  # buttonHoverTextColor = "white"
  # buttonHoverBgColor = "blue"
  # borderColor = "moon-gray"

  # more
  sidebarLinkColor = "near-black"
  footerTextColor = "gray"

  # show/hide social icons in site header/footer
  # content display
  recent_posts_number = 2
  show_reading_time = false

  socialInHeader = false
  socialInFooter = true

[social]
  github = "amanahuja"
  linkedin = "amanahuja"
  medium = ""
  twitter = ""
  youtube = ""
  mastodon = "amanqa"
  # no SVG: rss = "index.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[sitemap] 
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe=true

#   [markup.highlight]
#     style = "solarized-light"
     
